import type { LanguageDefinition } from "highlight.js/lib/core.js";
import bash from "highlight.js/lib/languages/bash.js";
import css from "highlight.js/lib/languages/css.js";
import diff from "highlight.js/lib/languages/diff.js";
import javascript from "highlight.js/lib/languages/javascript.js";
import json from "highlight.js/lib/languages/json.js";
import markdown from "highlight.js/lib/languages/markdown.js";
import python from "highlight.js/lib/languages/python.js";
import ruby from "highlight.js/lib/languages/ruby.js";
import typescript from "highlight.js/lib/languages/typescript.js";
import xml from "highlight.js/lib/languages/xml.js";
import yaml from "highlight.js/lib/languages/yaml.js";

type LanguageModule = { default: LanguageDefinition };

export interface HighlightLanguage {
	name: string;
	extensions?: readonly string[];
	aliases?: readonly string[];
	dependencies?: readonly string[];
	definition?: LanguageDefinition;
	load?: () => Promise<LanguageModule>;
}

// Registration, aliases, dependencies, lazy importers, and file-extension
// detection live in one registry.
//
// Intentional exception to the no-dynamic-import rule: literal dynamic imports
// let Bun embed every grammar in the standalone binary while keeping evaluation
// lazy, and let Node load only the requested grammar.
export const HIGHLIGHT_LANGUAGES: readonly HighlightLanguage[] = [
	{ name: "1c", load: () => import("highlight.js/lib/languages/1c.js") },
	{ name: "abnf", load: () => import("highlight.js/lib/languages/abnf.js") },
	{ name: "accesslog", load: () => import("highlight.js/lib/languages/accesslog.js") },
	{
		name: "actionscript",
		aliases: ["as"],
		load: () => import("highlight.js/lib/languages/actionscript.js"),
	},
	{ name: "ada", load: () => import("highlight.js/lib/languages/ada.js") },
	{
		name: "angelscript",
		aliases: ["asc"],
		load: () => import("highlight.js/lib/languages/angelscript.js"),
	},
	{
		name: "apache",
		aliases: ["apacheconf"],
		load: () => import("highlight.js/lib/languages/apache.js"),
	},
	{
		name: "applescript",
		aliases: ["osascript"],
		load: () => import("highlight.js/lib/languages/applescript.js"),
	},
	{ name: "arcade", load: () => import("highlight.js/lib/languages/arcade.js") },
	{ name: "arduino", aliases: ["ino"], load: () => import("highlight.js/lib/languages/arduino.js") },
	{ name: "armasm", aliases: ["arm"], load: () => import("highlight.js/lib/languages/armasm.js") },
	{
		name: "xml",
		extensions: ["xml"],
		aliases: ["html", "xhtml", "rss", "atom", "xjb", "xsd", "xsl", "plist", "wsf", "svg"],
		dependencies: ["css", "javascript"],
		definition: xml,
	},
	{ name: "html", extensions: ["html", "htm"], dependencies: ["xml"] },
	{
		name: "asciidoc",
		aliases: ["adoc"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/asciidoc.js"),
	},
	{ name: "aspectj", load: () => import("highlight.js/lib/languages/aspectj.js") },
	{
		name: "autohotkey",
		aliases: ["ahk"],
		load: () => import("highlight.js/lib/languages/autohotkey.js"),
	},
	{ name: "autoit", load: () => import("highlight.js/lib/languages/autoit.js") },
	{ name: "avrasm", load: () => import("highlight.js/lib/languages/avrasm.js") },
	{ name: "awk", load: () => import("highlight.js/lib/languages/awk.js") },
	{ name: "axapta", aliases: ["x++"], load: () => import("highlight.js/lib/languages/axapta.js") },
	{ name: "bash", extensions: ["sh", "bash", "zsh"], aliases: ["sh", "zsh"], definition: bash },
	{ name: "basic", load: () => import("highlight.js/lib/languages/basic.js") },
	{ name: "bnf", load: () => import("highlight.js/lib/languages/bnf.js") },
	{
		name: "brainfuck",
		aliases: ["bf"],
		load: () => import("highlight.js/lib/languages/brainfuck.js"),
	},
	{
		name: "c-like",
		aliases: ["c", "h", "cc", "c++", "h++", "hpp", "hh", "hxx", "cxx"],
		load: () => import("highlight.js/lib/languages/c-like.js"),
	},
	{ name: "c", extensions: ["c", "h"], aliases: ["h"], load: () => import("highlight.js/lib/languages/c.js") },
	{ name: "cal", load: () => import("highlight.js/lib/languages/cal.js") },
	{
		name: "capnproto",
		aliases: ["capnp"],
		load: () => import("highlight.js/lib/languages/capnproto.js"),
	},
	{ name: "ceylon", load: () => import("highlight.js/lib/languages/ceylon.js") },
	{
		name: "clean",
		aliases: ["icl", "dcl"],
		load: () => import("highlight.js/lib/languages/clean.js"),
	},
	{
		name: "clojure",
		extensions: ["clj"],
		aliases: ["clj"],
		load: () => import("highlight.js/lib/languages/clojure.js"),
	},
	{
		name: "clojure-repl",
		dependencies: ["clojure"],
		load: () => import("highlight.js/lib/languages/clojure-repl.js"),
	},
	{
		name: "cmake",
		extensions: ["cmake"],
		aliases: ["cmake.in"],
		load: () => import("highlight.js/lib/languages/cmake.js"),
	},
	{
		name: "coffeescript",
		aliases: ["coffee", "cson", "iced"],
		dependencies: ["javascript"],
		load: () => import("highlight.js/lib/languages/coffeescript.js"),
	},
	{ name: "coq", load: () => import("highlight.js/lib/languages/coq.js") },
	{
		name: "cos",
		aliases: ["cls"],
		dependencies: ["javascript", "sql", "xml"],
		load: () => import("highlight.js/lib/languages/cos.js"),
	},
	{
		name: "cpp",
		extensions: ["cpp", "cc", "cxx", "hpp"],
		aliases: ["cc", "c++", "h++", "hpp", "hh", "hxx", "cxx"],
		load: () => import("highlight.js/lib/languages/cpp.js"),
	},
	{
		name: "crmsh",
		aliases: ["crm", "pcmk"],
		load: () => import("highlight.js/lib/languages/crmsh.js"),
	},
	{ name: "crystal", aliases: ["cr"], load: () => import("highlight.js/lib/languages/crystal.js") },
	{
		name: "csharp",
		extensions: ["cs"],
		aliases: ["cs", "c#"],
		load: () => import("highlight.js/lib/languages/csharp.js"),
	},
	{ name: "csp", load: () => import("highlight.js/lib/languages/csp.js") },
	{ name: "css", extensions: ["css"], definition: css },
	{ name: "d", load: () => import("highlight.js/lib/languages/d.js") },
	{
		name: "markdown",
		extensions: ["md", "markdown"],
		aliases: ["md", "mkdown", "mkd"],
		dependencies: ["xml"],
		definition: markdown,
	},
	{
		name: "dart",
		dependencies: ["markdown"],
		load: () => import("highlight.js/lib/languages/dart.js"),
	},
	{
		name: "delphi",
		aliases: ["dpr", "dfm", "pas", "pascal", "freepascal", "lazarus", "lpr", "lfm"],
		load: () => import("highlight.js/lib/languages/delphi.js"),
	},
	{ name: "diff", aliases: ["patch"], definition: diff },
	{
		name: "django",
		aliases: ["jinja"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/django.js"),
	},
	{ name: "dns", aliases: ["bind", "zone"], load: () => import("highlight.js/lib/languages/dns.js") },
	{
		name: "dockerfile",
		extensions: ["dockerfile"],
		aliases: ["docker"],
		dependencies: ["bash"],
		load: () => import("highlight.js/lib/languages/dockerfile.js"),
	},
	{ name: "dos", aliases: ["bat", "cmd"], load: () => import("highlight.js/lib/languages/dos.js") },
	{ name: "dsconfig", load: () => import("highlight.js/lib/languages/dsconfig.js") },
	{ name: "dts", load: () => import("highlight.js/lib/languages/dts.js") },
	{
		name: "dust",
		aliases: ["dst"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/dust.js"),
	},
	{ name: "ebnf", load: () => import("highlight.js/lib/languages/ebnf.js") },
	{ name: "elixir", extensions: ["ex", "exs"], load: () => import("highlight.js/lib/languages/elixir.js") },
	{ name: "elm", load: () => import("highlight.js/lib/languages/elm.js") },
	{
		name: "ruby",
		extensions: ["rb"],
		aliases: ["rb", "gemspec", "podspec", "thor", "irb"],
		definition: ruby,
	},
	{
		name: "erb",
		dependencies: ["ruby", "xml"],
		load: () => import("highlight.js/lib/languages/erb.js"),
	},
	{ name: "erlang-repl", load: () => import("highlight.js/lib/languages/erlang-repl.js") },
	{
		name: "erlang",
		extensions: ["erl"],
		aliases: ["erl"],
		load: () => import("highlight.js/lib/languages/erlang.js"),
	},
	{
		name: "excel",
		aliases: ["xlsx", "xls"],
		load: () => import("highlight.js/lib/languages/excel.js"),
	},
	{ name: "fix", load: () => import("highlight.js/lib/languages/fix.js") },
	{ name: "fish", extensions: ["fish"] },
	{ name: "flix", load: () => import("highlight.js/lib/languages/flix.js") },
	{
		name: "fortran",
		aliases: ["f90", "f95"],
		load: () => import("highlight.js/lib/languages/fortran.js"),
	},
	{ name: "fsharp", aliases: ["fs"], load: () => import("highlight.js/lib/languages/fsharp.js") },
	{ name: "gams", aliases: ["gms"], load: () => import("highlight.js/lib/languages/gams.js") },
	{ name: "gauss", aliases: ["gss"], load: () => import("highlight.js/lib/languages/gauss.js") },
	{ name: "gcode", aliases: ["nc"], load: () => import("highlight.js/lib/languages/gcode.js") },
	{
		name: "gherkin",
		aliases: ["feature"],
		load: () => import("highlight.js/lib/languages/gherkin.js"),
	},
	{ name: "glsl", load: () => import("highlight.js/lib/languages/glsl.js") },
	{ name: "gml", load: () => import("highlight.js/lib/languages/gml.js") },
	{ name: "go", extensions: ["go"], aliases: ["golang"], load: () => import("highlight.js/lib/languages/go.js") },
	{ name: "golo", load: () => import("highlight.js/lib/languages/golo.js") },
	{ name: "gradle", load: () => import("highlight.js/lib/languages/gradle.js") },
	{ name: "graphql", extensions: ["graphql"] },
	{ name: "groovy", load: () => import("highlight.js/lib/languages/groovy.js") },
	{
		name: "haml",
		dependencies: ["ruby"],
		load: () => import("highlight.js/lib/languages/haml.js"),
	},
	{
		name: "handlebars",
		aliases: ["hbs", "html.hbs", "html.handlebars", "htmlbars"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/handlebars.js"),
	},
	{
		name: "haskell",
		extensions: ["hs"],
		aliases: ["hs"],
		load: () => import("highlight.js/lib/languages/haskell.js"),
	},
	{ name: "hcl", extensions: ["tf", "hcl"] },
	{ name: "haxe", aliases: ["hx"], load: () => import("highlight.js/lib/languages/haxe.js") },
	{ name: "hsp", load: () => import("highlight.js/lib/languages/hsp.js") },
	{
		name: "htmlbars",
		aliases: ["hbs", "html.hbs", "html.handlebars", "htmlbars"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/htmlbars.js"),
	},
	{ name: "http", aliases: ["https"], load: () => import("highlight.js/lib/languages/http.js") },
	{ name: "hy", aliases: ["hylang"], load: () => import("highlight.js/lib/languages/hy.js") },
	{ name: "inform7", aliases: ["i7"], load: () => import("highlight.js/lib/languages/inform7.js") },
	{ name: "ini", aliases: ["toml"], load: () => import("highlight.js/lib/languages/ini.js") },
	{ name: "irpf90", load: () => import("highlight.js/lib/languages/irpf90.js") },
	{ name: "isbl", load: () => import("highlight.js/lib/languages/isbl.js") },
	{ name: "java", extensions: ["java"], aliases: ["jsp"], load: () => import("highlight.js/lib/languages/java.js") },
	{
		name: "javascript",
		extensions: ["js", "jsx", "mjs", "cjs"],
		aliases: ["js", "jsx", "mjs", "cjs"],
		dependencies: ["css", "xml"],
		definition: javascript,
	},
	{
		name: "jboss-cli",
		aliases: ["wildfly-cli"],
		load: () => import("highlight.js/lib/languages/jboss-cli.js"),
	},
	{ name: "json", extensions: ["json"], definition: json },
	{ name: "julia", load: () => import("highlight.js/lib/languages/julia.js") },
	{
		name: "julia-repl",
		dependencies: ["julia"],
		load: () => import("highlight.js/lib/languages/julia-repl.js"),
	},
	{
		name: "kotlin",
		extensions: ["kt"],
		aliases: ["kt", "kts"],
		load: () => import("highlight.js/lib/languages/kotlin.js"),
	},
	{
		name: "lasso",
		aliases: ["ls", "lassoscript"],
		load: () => import("highlight.js/lib/languages/lasso.js"),
	},
	{ name: "latex", aliases: ["tex"], load: () => import("highlight.js/lib/languages/latex.js") },
	{ name: "ldif", load: () => import("highlight.js/lib/languages/ldif.js") },
	{ name: "leaf", load: () => import("highlight.js/lib/languages/leaf.js") },
	{ name: "less", extensions: ["less"], load: () => import("highlight.js/lib/languages/less.js") },
	{ name: "lisp", load: () => import("highlight.js/lib/languages/lisp.js") },
	{ name: "livecodeserver", load: () => import("highlight.js/lib/languages/livecodeserver.js") },
	{
		name: "livescript",
		aliases: ["ls"],
		dependencies: ["javascript"],
		load: () => import("highlight.js/lib/languages/livescript.js"),
	},
	{ name: "llvm", load: () => import("highlight.js/lib/languages/llvm.js") },
	{ name: "lsl", load: () => import("highlight.js/lib/languages/lsl.js") },
	{ name: "lua", extensions: ["lua"], load: () => import("highlight.js/lib/languages/lua.js") },
	{
		name: "makefile",
		extensions: ["makefile"],
		aliases: ["mk", "mak", "make"],
		load: () => import("highlight.js/lib/languages/makefile.js"),
	},
	{
		name: "mathematica",
		aliases: ["mma", "wl"],
		load: () => import("highlight.js/lib/languages/mathematica.js"),
	},
	{ name: "matlab", load: () => import("highlight.js/lib/languages/matlab.js") },
	{ name: "maxima", load: () => import("highlight.js/lib/languages/maxima.js") },
	{ name: "mel", load: () => import("highlight.js/lib/languages/mel.js") },
	{
		name: "mercury",
		aliases: ["m", "moo"],
		load: () => import("highlight.js/lib/languages/mercury.js"),
	},
	{ name: "mipsasm", aliases: ["mips"], load: () => import("highlight.js/lib/languages/mipsasm.js") },
	{ name: "mizar", load: () => import("highlight.js/lib/languages/mizar.js") },
	{
		name: "perl",
		extensions: ["perl"],
		aliases: ["pl", "pm"],
		dependencies: ["mojolicious"],
		load: () => import("highlight.js/lib/languages/perl.js"),
	},
	{
		name: "mojolicious",
		dependencies: ["perl", "xml"],
		load: () => import("highlight.js/lib/languages/mojolicious.js"),
	},
	{ name: "monkey", load: () => import("highlight.js/lib/languages/monkey.js") },
	{
		name: "moonscript",
		aliases: ["moon"],
		load: () => import("highlight.js/lib/languages/moonscript.js"),
	},
	{ name: "n1ql", load: () => import("highlight.js/lib/languages/n1ql.js") },
	{ name: "nginx", aliases: ["nginxconf"], load: () => import("highlight.js/lib/languages/nginx.js") },
	{ name: "nim", load: () => import("highlight.js/lib/languages/nim.js") },
	{ name: "nix", aliases: ["nixos"], load: () => import("highlight.js/lib/languages/nix.js") },
	{
		name: "node-repl",
		dependencies: ["javascript"],
		load: () => import("highlight.js/lib/languages/node-repl.js"),
	},
	{ name: "nsis", load: () => import("highlight.js/lib/languages/nsis.js") },
	{
		name: "objectivec",
		aliases: ["mm", "objc", "obj-c", "obj-c++", "objective-c++"],
		load: () => import("highlight.js/lib/languages/objectivec.js"),
	},
	{ name: "ocaml", extensions: ["ml"], aliases: ["ml"], load: () => import("highlight.js/lib/languages/ocaml.js") },
	{
		name: "openscad",
		aliases: ["scad"],
		load: () => import("highlight.js/lib/languages/openscad.js"),
	},
	{ name: "oxygene", load: () => import("highlight.js/lib/languages/oxygene.js") },
	{
		name: "parser3",
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/parser3.js"),
	},
	{ name: "pf", aliases: ["pf.conf"], load: () => import("highlight.js/lib/languages/pf.js") },
	{
		name: "pgsql",
		aliases: ["postgres", "postgresql"],
		dependencies: ["bash", "java", "json", "lua", "perl", "php", "python", "r", "ruby", "scheme", "tcl", "xml"],
		load: () => import("highlight.js/lib/languages/pgsql.js"),
	},
	{
		name: "php",
		extensions: ["php"],
		aliases: ["php3", "php4", "php5", "php6", "php7", "php8"],
		load: () => import("highlight.js/lib/languages/php.js"),
	},
	{
		name: "php-template",
		dependencies: ["php", "xml"],
		load: () => import("highlight.js/lib/languages/php-template.js"),
	},
	{
		name: "plaintext",
		aliases: ["text", "txt"],
		load: () => import("highlight.js/lib/languages/plaintext.js"),
	},
	{ name: "pony", load: () => import("highlight.js/lib/languages/pony.js") },
	{
		name: "powershell",
		extensions: ["ps1"],
		aliases: ["ps", "ps1"],
		load: () => import("highlight.js/lib/languages/powershell.js"),
	},
	{ name: "processing", load: () => import("highlight.js/lib/languages/processing.js") },
	{ name: "profile", load: () => import("highlight.js/lib/languages/profile.js") },
	{ name: "prolog", load: () => import("highlight.js/lib/languages/prolog.js") },
	{ name: "properties", load: () => import("highlight.js/lib/languages/properties.js") },
	{ name: "protobuf", extensions: ["proto"], load: () => import("highlight.js/lib/languages/protobuf.js") },
	{ name: "puppet", aliases: ["pp"], load: () => import("highlight.js/lib/languages/puppet.js") },
	{
		name: "purebasic",
		aliases: ["pb", "pbi"],
		load: () => import("highlight.js/lib/languages/purebasic.js"),
	},
	{ name: "python", extensions: ["py"], aliases: ["py", "gyp", "ipython"], definition: python },
	{
		name: "python-repl",
		aliases: ["pycon"],
		dependencies: ["python"],
		load: () => import("highlight.js/lib/languages/python-repl.js"),
	},
	{ name: "q", aliases: ["k", "kdb"], load: () => import("highlight.js/lib/languages/q.js") },
	{
		name: "qml",
		aliases: ["qt"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/qml.js"),
	},
	{ name: "r", extensions: ["r"], load: () => import("highlight.js/lib/languages/r.js") },
	{ name: "reasonml", aliases: ["re"], load: () => import("highlight.js/lib/languages/reasonml.js") },
	{ name: "rib", load: () => import("highlight.js/lib/languages/rib.js") },
	{
		name: "roboconf",
		aliases: ["graph", "instances"],
		load: () => import("highlight.js/lib/languages/roboconf.js"),
	},
	{
		name: "routeros",
		aliases: ["mikrotik"],
		load: () => import("highlight.js/lib/languages/routeros.js"),
	},
	{ name: "rsl", load: () => import("highlight.js/lib/languages/rsl.js") },
	{ name: "ruleslanguage", load: () => import("highlight.js/lib/languages/ruleslanguage.js") },
	{ name: "rust", extensions: ["rs"], aliases: ["rs"], load: () => import("highlight.js/lib/languages/rust.js") },
	{ name: "sas", load: () => import("highlight.js/lib/languages/sas.js") },
	{ name: "sass", extensions: ["sass"] },
	{ name: "scala", extensions: ["scala"], load: () => import("highlight.js/lib/languages/scala.js") },
	{ name: "scheme", load: () => import("highlight.js/lib/languages/scheme.js") },
	{ name: "scilab", aliases: ["sci"], load: () => import("highlight.js/lib/languages/scilab.js") },
	{ name: "scss", extensions: ["scss"], load: () => import("highlight.js/lib/languages/scss.js") },
	{
		name: "shell",
		aliases: ["console"],
		dependencies: ["bash"],
		load: () => import("highlight.js/lib/languages/shell.js"),
	},
	{ name: "smali", load: () => import("highlight.js/lib/languages/smali.js") },
	{
		name: "smalltalk",
		aliases: ["st"],
		load: () => import("highlight.js/lib/languages/smalltalk.js"),
	},
	{ name: "sml", aliases: ["ml"], load: () => import("highlight.js/lib/languages/sml.js") },
	{ name: "sqf", load: () => import("highlight.js/lib/languages/sqf.js") },
	{
		name: "sql_more",
		aliases: ["mysql", "oracle"],
		load: () => import("highlight.js/lib/languages/sql_more.js"),
	},
	{ name: "sql", extensions: ["sql"], load: () => import("highlight.js/lib/languages/sql.js") },
	{ name: "stan", aliases: ["stanfuncs"], load: () => import("highlight.js/lib/languages/stan.js") },
	{ name: "stata", aliases: ["do", "ado"], load: () => import("highlight.js/lib/languages/stata.js") },
	{
		name: "step21",
		aliases: ["p21", "step", "stp"],
		load: () => import("highlight.js/lib/languages/step21.js"),
	},
	{ name: "stylus", aliases: ["styl"], load: () => import("highlight.js/lib/languages/stylus.js") },
	{ name: "subunit", load: () => import("highlight.js/lib/languages/subunit.js") },
	{ name: "swift", extensions: ["swift"], load: () => import("highlight.js/lib/languages/swift.js") },
	{ name: "taggerscript", load: () => import("highlight.js/lib/languages/taggerscript.js") },
	{
		name: "yaml",
		extensions: ["yaml", "yml"],
		aliases: ["yml"],
		dependencies: ["ruby"],
		definition: yaml,
	},
	{
		name: "tap",
		dependencies: ["yaml"],
		load: () => import("highlight.js/lib/languages/tap.js"),
	},
	{ name: "tcl", aliases: ["tk"], load: () => import("highlight.js/lib/languages/tcl.js") },
	{ name: "thrift", load: () => import("highlight.js/lib/languages/thrift.js") },
	{ name: "toml", extensions: ["toml"], dependencies: ["ini"] },
	{ name: "tp", load: () => import("highlight.js/lib/languages/tp.js") },
	{
		name: "twig",
		aliases: ["craftcms"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/twig.js"),
	},
	{
		name: "typescript",
		extensions: ["ts", "tsx"],
		aliases: ["ts", "tsx"],
		dependencies: ["css", "xml"],
		definition: typescript,
	},
	{ name: "vala", load: () => import("highlight.js/lib/languages/vala.js") },
	{ name: "vbnet", aliases: ["vb"], load: () => import("highlight.js/lib/languages/vbnet.js") },
	{ name: "vbscript", aliases: ["vbs"], load: () => import("highlight.js/lib/languages/vbscript.js") },
	{
		name: "vbscript-html",
		dependencies: ["vbscript", "xml"],
		load: () => import("highlight.js/lib/languages/vbscript-html.js"),
	},
	{
		name: "verilog",
		aliases: ["v", "sv", "svh"],
		load: () => import("highlight.js/lib/languages/verilog.js"),
	},
	{ name: "vhdl", load: () => import("highlight.js/lib/languages/vhdl.js") },
	{ name: "vim", extensions: ["vim"], load: () => import("highlight.js/lib/languages/vim.js") },
	{ name: "x86asm", load: () => import("highlight.js/lib/languages/x86asm.js") },
	{ name: "xl", aliases: ["tao"], load: () => import("highlight.js/lib/languages/xl.js") },
	{
		name: "xquery",
		aliases: ["xpath", "xq"],
		dependencies: ["xml"],
		load: () => import("highlight.js/lib/languages/xquery.js"),
	},
	{ name: "zephir", aliases: ["zep"], load: () => import("highlight.js/lib/languages/zephir.js") },
];
